FROM node:14 AS dependencies
WORKDIR /usr/src/app
COPY package.json yarn.lock  ./
COPY shared/package.json ./shared/
COPY frontend/package.json ./frontend/
COPY backend/package.json ./backend/
RUN yarn

FROM dependencies AS shared
WORKDIR /usr/src/app
COPY ./shared ./shared/
RUN yarn shared build

FROM shared AS build-frontend
WORKDIR /usr/src/app
COPY ./frontend ./frontend/
RUN yarn frontend build

FROM nginx:stable-alpine
COPY --from=build-frontend /usr/src/app/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
